apiVersion: apps/v1
kind: Deployment
metadata:
  name: prt-deployment

spec:
  replicas: 2

  selector:
    matchLabels:
      app: prt-cicd-app

  template:
    metadata:
      labels:
        app: prt-cicd-app

    spec:
      containers:
      - name: prt-container
        image: samiksha1195/prt-cicd-app:latest

        ports:
        - containerPort: 80
